#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${1:-$ROOT_DIR/host-software}"

mkdir -p "$OUT_DIR"

write_metadata() {
  {
    echo "# Generated by scripts/export-host-software.sh"
    echo "generated_at=$(date -Is)"
    echo "hostname=$(hostname)"
    echo "kernel=$(uname -srmo)"
    if [[ -f /etc/os-release ]]; then
      awk -F= '/^(ID|VERSION_ID|VERSION_CODENAME|PRETTY_NAME)=/ { print }' /etc/os-release
    fi
  } > "$OUT_DIR/metadata.env"
}

installed_dpkg_version() {
  local package="$1"
  dpkg-query -W -f='${Version}' "$package" 2>/dev/null || true
}

installed_cmd_version() {
  local cmd="$1"
  if command -v "$cmd" >/dev/null 2>&1; then
    "$cmd" --version 2>/dev/null | head -n 1 || command -v "$cmd"
  fi
}

write_major_apps() {
  local file="$OUT_DIR/major-apps.tsv"
  {
    printf '# name\tkind\tinstall_method\tpackage_or_command\tinstalled_version\tnote\n'
    printf 'Docker\tcore\tofficial-script\tdocker\t%s\tDocker Engine and Compose plugin; bootstrap installs this before MCSManager.\n' "$(installed_cmd_version docker)"
    printf 'Codex CLI\tdev-tool\tofficial-script\tcodex\t%s\tOpenAI Codex CLI; bootstrap installs this with the official installer.\n' "$(installed_cmd_version codex)"
    printf 'Visual Studio Code\tdesktop-app\tapt\tcode\t%s\tLarge desktop app; requires Microsoft apt source or official .deb.\n' "$(installed_dpkg_version code)"
    printf 'Google Chrome\tdesktop-app\tapt\tgoogle-chrome-stable\t%s\tLarge desktop app; requires Google apt source or official .deb.\n' "$(installed_dpkg_version google-chrome-stable)"
    printf 'NoMachine\tremote-desktop\tapt\tnomachine\t%s\tInstall from official .deb if apt source is unavailable.\n' "$(installed_dpkg_version nomachine)"
    printf 'ToDesk\tremote-desktop\tapt\ttodesk\t%s\tInstall from official .deb if apt source is unavailable.\n' "$(installed_dpkg_version todesk)"
    printf 'Ghostty\tterminal\tapt\tghostty\t%s\tTerminal app; install only if package is available on the target host.\n' "$(installed_dpkg_version ghostty)"
    printf 'Clash Verge\tnetwork-tool\tapt\tclash-verge\t%s\tProxy client; install only if package/source is available on the target host.\n' "$(installed_dpkg_version clash-verge)"
    printf 'cc-switch\tdev-tool\tapt\tcc-switch\t%s\tCLI helper; install only if package/source is available on the target host.\n' "$(installed_dpkg_version cc-switch)"
  } > "$file"
}

write_vscode_extensions() {
  if ! command -v code >/dev/null 2>&1; then
    return
  fi

  code --list-extensions | sort > "$OUT_DIR/vscode-extensions.txt"
}

write_docker_images() {
  cat > "$OUT_DIR/docker-images.txt" <<'EOF'
# Docker images to pre-pull or rebuild on a new host.
# Keep this list high-level. Do not export every local image/cache layer.
#
# Minecraft Java default strategy:
# - Java 8: old Forge and many 1.12-1.16 modded servers.
# - Java 17: 1.18-1.20.4 and the current 1.20.1 modded pack in this repo.
# - Java 21: 1.20.5+ / 1.21.x servers.
# Add Java 11, 16, or 25 only when a specific server/Paper version requires it.
eclipse-temurin:8-jre
eclipse-temurin:17-jre
eclipse-temurin:21-jre
githubyumao/mcsmanager-web:latest
githubyumao/mcsmanager-daemon:latest
githubyumao/steam-game-runtime:latest
EOF
}

write_metadata
write_major_apps
write_vscode_extensions
write_docker_images

cat <<EOF
Exported curated host software manifest to:
  $OUT_DIR

Use on a new host:
  INSTALL_HOST_SOFTWARE=1 ./scripts/bootstrap-new-host.sh
EOF
